//package com.softlabs.aicontents;
//
//import org.junit.jupiter.api.Test;
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.boot.test.context.SpringBootTest;
//import org.springframework.jdbc.core.JdbcTemplate;
//
//
//import static org.assertj.core.api.Assertions.assertThat;
//
//
//import javax.sql.DataSource;
//import java.sql.Connection;
//import java.util.List;
//import java.util.Map;
//
//@SpringBootApplication(scanBasePackages = "com.softlabs.aicontents")
//public class RdsConnectionTest {
//
//    @Autowired
//    private DataSource dataSource;
//
//    @Autowired
//    private JdbcTemplate jdbcTemplate;
//
//    @Test
//    void testBasicRdsConnection() {
//        System.out.println(" RDS 연결 테이스________");
//
//        try(Connection connection = dataSource.getConnection()){
//
//            //연결 성공 검증
//            assertThat(connection).isNotNull();
//            assertThat(connection.isValid(10)).isTrue();
//
//            //연결 정보 출력
//            System.out.println("RDS 연결 성공 ");
//            System.out.println("DB URL : "+ connection.getMetaData().getURL());
//            System.out.println("사용자: " + connection.getMetaData().getUserName());
//            System.out.println("DB 제품 :" + connection.getMetaData().getDatabaseProductName());
//            System.out.println(" 버전 : " + connection.getMetaData().getDatabaseProductVersion());
//
//        } catch(Exception e) {
//            System.out.println(" RDS 연결 실패: " + e.getMessage());
//            e.printStackTrace();
//            throw new RuntimeException("RDS 연결 실패 ",e );
//        }
//
//    }
//
//
//    @Test
//    void testBasicQuery(){
//        System.out.println("기본 쿼리 테스트");
//
//        try{
//            //Oracle 기본 쿼리 실행
//            Map<String,Object> result = jdbcTemplate.queryForMap(
//                    "Select "+
//                            "'AWS RDS Oracle 쿼리 성공!! 'as message," +
//                            "TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS CURRENT_TIME,"+
//                            "USER as CURRENT_USER," +
//                            "SYS_CONTEXT('USERENV','DB_NAME') as DATABASE_NAME"+
//                            "FROM dual"
//            );
//
//            assertThat(result).isNotNull();
//            assertThat(result.get("MESSAGE")).isEqualTo("AWS RDS Oracle 쿼리 성공!! ");
//
//            System.out.println("쿼리 실행 성공");
//            System.out.println(" 메세지 "+result.get("MESSAGE"));
//            System.out.println(" 현재시간: "+ result.get("CURRENT_TIME"));
//            System.out.println(" 사용자: "+result.get("CURRENT_USER"));
//            System.out.println( "DB 이름 :" + result.get("DATABASE_NAME"));
//
//        } catch(Exception e) {
//            System.err.println("쿼리 실행 실패 : "+ e.getMessage());
//            e.printStackTrace();
//            throw new RuntimeException("쿼리 실행 실패",e);
//        }
//    }
//    @Test
//    void testTableCreation(){
//        System.out.println("~~~~테이블 생성 테스트~~~~");
//
//        try {
//            //테스트용 테이블 생성
//            String createTableSql  = """
//
//                    CREATE TABLE scheduler_test (
//                   test_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//                   test_message VARCHAR2(200),
//                   created_at TIMESTAMP DEFAULT SYSTIMESTAMP
//                    )
//                    """;
//            jdbcTemplate.execute(createTableSql );
//
//            System.out.println("테이블 생성 성공: scheduler_test");
//
//            //데이터 삽입 테스트
//            jdbcTemplate.update(
//                    " INSERT INTO scheduler_test(test_message) values (?)",
//                    "RDS 연결 테스트 성공!!!"
//            );
//            System.out.println("데이터 삽입 성공");
//
//            //데이터 조회 테스트
//            List<Map<String, Object>> result = jdbcTemplate.queryForList(
//                    "SELECT test_id, test_message, TO_CHAR(created_at, 'YYYY-MM-DD HH24:MI:SS') as created_time " +
//                            "FROM scheduler_test ORDER BY test_id DESC"
//            );
//
//            assertThat(result).isNotNull();
//            System.out.println("데이터 조회  성 공 "+result.size()+"건");
//
//            for(Map<String, Object> row : result){
//                System.out.println("ID"+row.get("TEST_ID") +", 메세지: " +row.get("TEST_MESSAGE")+
//                        ", 시간" +row.get("created_time"));
//            }
//
//            //테스트 테이블 삭제
//            jdbcTemplate.execute("DROP TABLE scheduler_test");
//            System.out.println("테스트 테이블 삭제 완료 ");
//
//        }  catch(Exception e) {
//            System.err.println("테이블 테스트 실패 : "+e.getMessage());
//            e.printStackTrace();
//            throw new RuntimeException("테이블 테스트 실패",e);
//        }
//    }
//
//    @Test
//    void testConnectionPooling() {
//        System.out.println("🏊 === 커넥션 풀 테스트 ===");
//
//        try {
//            // 여러 연결 동시 테스트 (커넥션 풀 검증)
//            for (int i = 1; i <= 3; i++) {
//                try (Connection conn = dataSource.getConnection()) {
//                    String result = jdbcTemplate.queryForObject(
//                            "SELECT 'Connection #" + i + " - ' || TO_CHAR(SYSDATE, 'HH24:MI:SS') FROM dual",
//                            String.class
//                    );
//
//                    System.out.println("   🔗 " + result);
//                    assertThat(result).contains("Connection #" + i);
//                }
//            }
//
//            System.out.println("✅ 커넥션 풀 테스트 성공!");
//
//        } catch (Exception e) {
//            System.err.println("💥 커넥션 풀 테스트 실패: " + e.getMessage());
//            throw new RuntimeException("커넥션 풀 테스트 실패", e);
//        }
//    }
//}
//
